[project]
name = "gait-40-dof-22-musc-sagittal"
version = "0.1.0"
description = "A 2D constrained version of the 40 dof 22 muscle humanoid from MyoSuite"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "myosuite"
]

